### ISSUE TITLE
Footer doesn't belong to the end of the page

### ISSUE THREAD

**Issue by SKProCH** [yaroslaff/okerr-dev#11]
If we look at okerr pages, we can notice that the footer is floating on the page, while it should be it the bottom of the page. 

![image](https://github.com/yaroslaff/okerr-dev/assets/29896317/6d372c2a-4173-4def-9018-f9c18137709c)

**Comment by yaroslaff** [comment]
Yes, I agree. Thank you for report. For now do not have time to fix it, but will fix it when I will get time.  I tried, but seems simple changes (`position: fixed; bottom: 0;`) do not really work - footer overlaps with page content if page has many indicators and takes 100+% of height of screen.

But I will accept pull request to styles.css or base.html if someone will make it.

**Comment by SKProCH** [comment]
I didn't has so much experience in styling, but for my experience it can be resolved with css flexbox. I'll take a look if i can fix it, and probably submit a PR.

**Comment by yaroslaff** [comment]
Please check new style - footer is on bottom now. (Thanks to ChatGPT!)

**Comment by SKProCH** [comment]
Seems like everything working as expected now. Thanks!
